/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const slots = pgTable(
  "slots",
  {
    id: serial("id").primaryKey(),
    startTime: varchar("start_time").notNull(),
    endTime: varchar("end_time").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("slots_updated_at_idx").on(columns.updatedAt),
    index("slots_created_at_idx").on(columns.createdAt),
  ],
);

export const appointment_dates = pgTable(
  "appointment_dates",
  {
    id: serial("id").primaryKey(),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("appointment_dates_updated_at_idx").on(columns.updatedAt),
    index("appointment_dates_created_at_idx").on(columns.createdAt),
  ],
);

export const appointment_dates_rels = pgTable(
  "appointment_dates_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "appointment-slotsID": integer("appointment_slots_id"),
  },
  (columns) => [
    index("appointment_dates_rels_order_idx").on(columns.order),
    index("appointment_dates_rels_parent_idx").on(columns.parent),
    index("appointment_dates_rels_path_idx").on(columns.path),
    index("appointment_dates_rels_appointment_slots_id_idx").on(
      columns["appointment-slotsID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [appointment_dates.id],
      name: "appointment_dates_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["appointment-slotsID"]],
      foreignColumns: [appointment_slots.id],
      name: "appointment_dates_rels_appointment_slots_fk",
    }).onDelete("cascade"),
  ],
);

export const appointment_slots = pgTable(
  "appointment_slots",
  {
    id: serial("id").primaryKey(),
    slot: integer("slot_id")
      .notNull()
      .references(() => slots.id, {
        onDelete: "set null",
      }),
    appointment_date: integer("appointment_date_id")
      .notNull()
      .references(() => appointment_dates.id, {
        onDelete: "set null",
      }),
    appointment: integer("appointment_id").references(() => appointments.id, {
      onDelete: "set null",
    }),
    booked: boolean("booked").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("appointment_slots_slot_idx").on(columns.slot),
    index("appointment_slots_appointment_date_idx").on(
      columns.appointment_date,
    ),
    index("appointment_slots_appointment_idx").on(columns.appointment),
    index("appointment_slots_updated_at_idx").on(columns.updatedAt),
    index("appointment_slots_created_at_idx").on(columns.createdAt),
  ],
);

export const appointments = pgTable(
  "appointments",
  {
    id: serial("id").primaryKey(),
    customerName: varchar("customer_name").notNull(),
    customerPhone: varchar("customer_phone").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("appointments_updated_at_idx").on(columns.updatedAt),
    index("appointments_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    slotsID: integer("slots_id"),
    "appointment-datesID": integer("appointment_dates_id"),
    "appointment-slotsID": integer("appointment_slots_id"),
    appointmentsID: integer("appointments_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_slots_id_idx").on(columns.slotsID),
    index("payload_locked_documents_rels_appointment_dates_id_idx").on(
      columns["appointment-datesID"],
    ),
    index("payload_locked_documents_rels_appointment_slots_id_idx").on(
      columns["appointment-slotsID"],
    ),
    index("payload_locked_documents_rels_appointments_id_idx").on(
      columns.appointmentsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["slotsID"]],
      foreignColumns: [slots.id],
      name: "payload_locked_documents_rels_slots_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["appointment-datesID"]],
      foreignColumns: [appointment_dates.id],
      name: "payload_locked_documents_rels_appointment_dates_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["appointment-slotsID"]],
      foreignColumns: [appointment_slots.id],
      name: "payload_locked_documents_rels_appointment_slots_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["appointmentsID"]],
      foreignColumns: [appointments.id],
      name: "payload_locked_documents_rels_appointments_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_slots = relations(slots, () => ({}));
export const relations_appointment_dates_rels = relations(
  appointment_dates_rels,
  ({ one }) => ({
    parent: one(appointment_dates, {
      fields: [appointment_dates_rels.parent],
      references: [appointment_dates.id],
      relationName: "_rels",
    }),
    "appointment-slotsID": one(appointment_slots, {
      fields: [appointment_dates_rels["appointment-slotsID"]],
      references: [appointment_slots.id],
      relationName: "appointment-slots",
    }),
  }),
);
export const relations_appointment_dates = relations(
  appointment_dates,
  ({ many }) => ({
    _rels: many(appointment_dates_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_appointment_slots = relations(
  appointment_slots,
  ({ one }) => ({
    slot: one(slots, {
      fields: [appointment_slots.slot],
      references: [slots.id],
      relationName: "slot",
    }),
    appointment_date: one(appointment_dates, {
      fields: [appointment_slots.appointment_date],
      references: [appointment_dates.id],
      relationName: "appointment_date",
    }),
    appointment: one(appointments, {
      fields: [appointment_slots.appointment],
      references: [appointments.id],
      relationName: "appointment",
    }),
  }),
);
export const relations_appointments = relations(appointments, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    slotsID: one(slots, {
      fields: [payload_locked_documents_rels.slotsID],
      references: [slots.id],
      relationName: "slots",
    }),
    "appointment-datesID": one(appointment_dates, {
      fields: [payload_locked_documents_rels["appointment-datesID"]],
      references: [appointment_dates.id],
      relationName: "appointment-dates",
    }),
    "appointment-slotsID": one(appointment_slots, {
      fields: [payload_locked_documents_rels["appointment-slotsID"]],
      references: [appointment_slots.id],
      relationName: "appointment-slots",
    }),
    appointmentsID: one(appointments, {
      fields: [payload_locked_documents_rels.appointmentsID],
      references: [appointments.id],
      relationName: "appointments",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  slots: typeof slots;
  appointment_dates: typeof appointment_dates;
  appointment_dates_rels: typeof appointment_dates_rels;
  appointment_slots: typeof appointment_slots;
  appointments: typeof appointments;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_slots: typeof relations_slots;
  relations_appointment_dates_rels: typeof relations_appointment_dates_rels;
  relations_appointment_dates: typeof relations_appointment_dates;
  relations_appointment_slots: typeof relations_appointment_slots;
  relations_appointments: typeof relations_appointments;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
